### ISSUE TITLE
[Feature] Add a bash trigger

### ISSUE THREAD

**Issue by djmgit** [djmgit/SaberX#5]
There should be a bash trigger for Saberx. The trigger will basically fire a user command and depending on the output of the command or the exit code of the command, the trigger will get fired and action will be taken.

The command can also be a user written script. The following can be a prospective template for the trigger.

```
trigger:
      type: BASH_TRIGGER
      check: "command to be executed"
      response: "expected response"
      exitcode: "expected exit code"
    execute:
    - "some action"
```
